query GetThreadById($id: String!) {
  getThreadById(threadId: $id) {
    data {
      id
      title
      content
      createdBy {
        id
        username
      }
      createdAt
      updatedAt
      updated
      views
    }
    error
  }
}
