query GetAllThread($limit: Int, $cursor: String) {
  getAllThread(limit: $limit, cursor: $cursor) {
    data {
      id
      title
      content
      updated
      createdBy {
        id
        username
      }
      comments {
        id
      }
      createdAt
      updatedAt
      views
    }
    error
  }
}
